### ISSUE TITLE
ARGUS configuration: replace filecopy by metaconfig

### ISSUE THREAD

**Issue by jouvin** [quattor/template-library-grid#139] opened 2015-05-05 14:23 UTC
As discussed/agreed in #134.

**Comment by jrha** [comment] 2015-05-05 14:24
Duplicate of #138.

**Closed by jrha** 2015-05-05 14:24 UTC
Labels: duplicate

**Comment by jouvin** [comment] 2015-05-05 14:25
sorry we did it at the same time! I checked just after you closed #134 and saw there was no issue open yet...

**Comment by jrha** [comment] 2015-05-05 15:00
:grinning:
